### GET request to example server
GET http://localhost:8080

###

GET http://localhost:8080/api/v1/software-engineers/getAllSoftwareEngineers

###

GET http://localhost:8080/api/v1/software-engineers/getSoftwareEngineer/1

###

POST http://localhost:8080/api/v1/software-engineers/addSoftwareEngineer
Content-Type: application/json

{
  "name": "Sophie Müller",
  "designation": "Full Stack Developer",
  "email": "sophie.mueller@gmail.com",
  "phone": "+4915782345678",
  "address": "Munich, Germany",
  "techStack": [
    "Java",
    "Spring Boot",
    "Angular",
    "PostgreSQL"
  ]
}

###

DELETE http://localhost:8080/api/v1/software-engineers/deleteSoftwareEngineer/

###

PUT http://localhost:8080/api/v1/software-engineers/updateSoftwareEngineer/8
Content-Type: application/json

{
  "name": "Emma Johansson",
  "designation": "UI/UX Designer",
  "email": "emma.johansson@designhub.com",
  "phone": "+46731234567",
  "address": "Stockholm, Sweden",
  "techStack": [
    "Figma",
    "Adobe XD",
    "Sketch",
    "HTML",
    "CSS"
  ]
}